#################
# cloud configs #
#################
server.port: 5555

spring.datasource:
    url: ...
    username: ...
    password: ...
    driver-class-name: ...

#server.ssl:
#  key-store: ...
#  key-store-password: ...
#  key-store-type: ...
#  key-alias: ...
#  ciphers: ...

settings:
  cors_origin: ...

management.endpoints.web.exposure.include: ...
  